[project]
name = "digit-recognizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pygame>=2.6.1",
    "tensorflow>=2.20.0",
]
[tool.pyright]
venvPath = "."
venv = ".venv"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
